services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 config.wsgi
    volumes:
      - .:/code
      - media_volume:/code/media
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db

    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - DB_NAME=image_processor
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
  celery:
    build: .
    command: >
      celery -A config worker --loglevel=info
      --concurrency=4 -n worker1@%%h
      -Q celery,high_priority
    volumes:
      - .:/code
    depends_on:
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    healthcheck:
      test: [ "CMD-SHELL", "celery inspect ping -A config -d celery@$$HOSTNAME" ]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=image_processor
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres_data:
  media_volume: